### ISSUE TITLE
Resolve variable in table transformers

### ISSUE THREAD

**Issue by ikalinin1** [vividus-framework/vividus#105]
{transformer=ITERATING, limit=${iterations}}

Actual behavior: 
Fails during examples table instantiation;

Expected behavior:
**iterations** will be resolved and passed as a parameter to the transformer

**Comment by valfirst** [comment]
Done, changes:
- https://github.com/vividus-framework/jbehave-core/commit/ba5f6a9a93cc925bb5e0000d4f3148772b2f6b23
 - https://github.com/vividus-framework/vividus/commit/da4f62686df1fac33206f9b0788a78bbf0651164

Example of usage: https://github.com/vividus-framework/vividus/commit/29088e003b28fe647ff5972a8083d1701e9aeb97
