### ISSUE TITLE
Scenario order has meaning when batch failures shouldn't be ignored

### ISSUE THREAD

**Issue by dKatechev** [vividus-framework/vividus#1093]
**Description:**
Launch two batches with next significant details:
**Configuration:**
```bdd.batch-1.ignore-failure=false```
**First batch story:**
```
Scenario: should fail
Then `2` is = `3`

Scenario: should pass
Then `2` is = `2`
```
**Expected behavior:**
The first batch has failed, the second batch shouldn't be launched.
**Actual behavior:**
Both batches are launched.

**Note:**
If the first branch last scenario is failed, the second branch won't be launched.

**Comment by valfirst** [comment]
The actual issue ([JBEHAVE-1372](https://jbehave.atlassian.net/browse/JBEHAVE-1372)) was fixed by https://github.com/jbehave/jbehave-core/pull/302. The changes from #1112 contains upgrade to the newer version of JBehave with the fix.
