### ISSUE TITLE
Possibility to stop some/all process on the newly opened page

### ISSUE THREAD

**Issue by AliakseiTsiarnouski** [vividus-framework/vividus#1103]
I would like to have possibility to stop some/all process on the newly opened page.

Example of usage when was a problem: 
- I open new window
- try to switch into newly opened window

it was not possible to do - because some element was not loaded fully (this case was with background image) and step "When I switch to window with title that is equal to `titleName`" was not performed = my story was not ended well.

**Comment by ikalinin1** [comment]
closed as a duplicate of #1104
