### ISSUE TITLE
Add ability to work with DynamoDB

### ISSUE THREAD

**Issue by AngelinaMarchyk** [vividus-framework/vividus#1175]
Could you please add ability to work with DynamoDB?
List of operations needed:
GetItem
Query 
UpdateItem needed as well, but not in priority

**Comment by AliakseiTsiarnouski** [comment]
Dear dev team, could you please take into account while "Query" operation implementation that it would be great (and for our team necessary) to have possibility to "wait" time while recording appears or update some of its values.

Examples: 
1) wait -> add possibility to make "wait period" while file appears (it might be 10-30 seconds or 6-7 minutes for waiting). as example - refresh every 5 second while expected file will appeared
2) add possibility for waiting when some of attributes of our recording will be changed.   
example -> I found recording by "fileName" part (...201207T142421885.xml) and it has "sts"="Pending"  
I want to check that "sts" (status) will be changed and appears "sts"="Processed"

**Comment by valfirst** [comment]
@AliakseiTsiarnouski due to priority changes, your request will be implemented later, please, convert the comment to a new ticket
