### ISSUE TITLE
DynamoDB plugin updating

### ISSUE THREAD

**Issue by AliakseiTsiarnouski** [vividus-framework/vividus#1235]
I would like to enhance existing DynamoDB plugin`s functionality and make possibility to set "wait" time while recording appears or update some of its values in case it is already set "by default". ->"Query/GetItem" operation 

Examples:

wait -> add possibility to make "wait period" while file appears (it might be 10-30 seconds or 6-7 minutes for waiting). as example - refresh every 5 second while expected file will appeared
add possibility for waiting when some of attributes of our recording will be changed.
example -> I found recording by "fileName" part (...201207T142421885.xml) and it has "sts"="Pending"
I want to check that "sts" (status) will be changed and appears "sts"="Processed"

DynamoDB plugin => https://github.com/vividus-framework/vividus/issues/1175

**Comment by valfirst** [comment]
Example: https://github.com/vividus-framework/vividus/blob/7e6a220cd9b5cbf0ce7065497315f11979c1774d/vividus-tests/src/main/resources/story/system/AWS%20-%20DynamoDB.story#L83-L98
