### ISSUE TITLE
error String index out of range: -1 when using variables in name in variables in composite steps parameter table

### ISSUE THREAD

**Issue by AliakseiSiliankou** [vividus-framework/vividus#1303]
**Describe the bug**
error when using names of variables in names of variables in composite steps parameter  table 

**To Reproduce**
1. run story with composite steps parameter table and names of variables in names of variables e.g.:
```gherkin
When I initialize the STORY variable `AdjPV` with value `10`
When I initialize the STORY variable `AdjBV` with value `13.2`
When I initialize the STORY variable `NewfiscalYearStart` with value `202109`
When I initialize the STORY variable `num` with value `1`
When I initialize the STORY variable `orderNum${num}_${NewfiscalYearStart}` with value `#{generateDate(P, yyyyMMddHHmmss)}`
When I initialize the STORY variable `orderNum` with value `#{generateDate(P, yyyyMMddHHmmss)}`
When I initialize the STORY variable `todayDtTm1` with value `#{generateDate(-P2M, yyyy-MM-dd'T'HH:mm:ss)}`
When I initialize the STORY variable `1legId` with value `12345`
When I submit order with paramaters:
|AboNumber          |Period               |OrderNumber                            |CountryCode    |TransactionCode|TransactionDate|OrderDate    |SequenceNumber                         |OrderAbo      |WarehouseCode|AddedPV |AddedBV |interfaceAttribute|
|${${num}legId}     |${NewfiscalYearStart}|${orderNum${num}_${NewfiscalYearStart}}|<AffLocale>    |AAA            |${todayDtTm1}  |${todayDtTm1}|${orderNum${num}_${NewfiscalYearStart}}|${${num}legId}|<wrhCD>      |${AdjPV}|${AdjBV}|positive          |
```
Actual Result: error appears
`String index out of range: -1`
**Expected behavior**
No error appears. Values of variables are used in composite steps parameter  table 

**Artifacts**
![image](https://user-images.githubusercontent.com/66690521/103549808-008ba480-4eb9-11eb-9721-53f80abc6315.png)
![image](https://user-images.githubusercontent.com/66690521/103549842-0ed9c080-4eb9-11eb-8ccc-7212c2757e89.png)

**Execution environment (please complete the following information):**
 vividusVersion = '0.2.13'
 vividusVersion = '0.2.14'

**Comment by AliakseiSiliankou** [comment]
[story_to_run.zip](https://github.com/vividus-framework/vividus/files/5765420/story_to_run.zip)

**Comment by AliakseiSiliankou** [comment]
[begining_of_composite.zip](https://github.com/vividus-framework/vividus/files/5770105/begining_of_composite.zip)

**Comment by abudevich** [comment]
Scenario for reproducing:

```
When I initialize the STORY variable `num` with value `1`
When I initialize the STORY variable `orderNum1` with value `12345`
When I initialize STORY variable `parametersMap` with values:
|OrderNumber      |SequenceNumber   |
|${orderNum${num}}|${orderNum${num}}|
```
