### ISSUE TITLE
Composite steps should not view their content in the Jira XRay artifacts as the result of export

### ISSUE THREAD

**Issue by cherevachy** [vividus-framework/vividus#1362]
**Describe the bug**
Composite steps become expanded (the list of embedded steps is visible in the Jira XRay artifacts) as the result of export

**To Reproduce**
Export to JIRA any VIVIDUS scenario that contains composite steps.

**Expected behavior**
Only the composite step itself should be displayed in the Jira XRay artifacts as the result of export - to make the description in JIRA easier to comprehend

**Comment by uarlouski** [comment]
https://github.com/jbehave/jbehave-core/commit/3ca6dc0d23253f70492ab4b433783d475106de41

**Comment by valfirst** [comment]
Fixed by #1428
