### ISSUE TITLE
Updating Vividus` plugin "AWS" in order to DynamoDB steps will allow to use ARN in its queries.

### ISSUE THREAD

**Issue by AliakseiTsiarnouski** [vividus-framework/vividus#1370]
Based on project needs it would be great to update Vividus` plugin "AWS" in order to DynamoDB steps will allow to use Amazon Resource Name (ARN) in its queries.

Example: 
at the moment step "Execute SELECT statement and validate result" provide possibility to refer to any table with table name

When I execute query `
    SELECT * FROM Music
    WHERE Artist='Roxette' and SongTitle='The Look'
` against DynamoDB and save result as JSON to scenario variable `song`

I would like to have possibility to use (ARN) when I make query

When I execute query `
    SELECT * FROM arn:aws:dynamodb:us-east-1:736277357201:table/ABOPayments-dev
    WHERE Artist='Roxette' and SongTitle='The Look'
` against DynamoDB and save result as JSON to scenario variable `song`

**Comment by valfirst** [comment]
Initial setup is needed: https://aws.amazon.com/blogs/aws/delegating-api-access-to-aws-services-using-iam-roles/
