### ISSUE TITLE
 Step "When I scroll to the end of the page" does not work in Vividus` version: '0.3.0-SNAPSHOT'

### ISSUE THREAD

**Issue by AliakseiTsiarnouski** [vividus-framework/vividus#1373]
**Description:**  Step "When I scroll to the end of the page" does not work in Vividus` version: '0.3.0-SNAPSHOT'

**STR:**
Try to run story twice: 1) with version: '0.3.0-SNAPSHOT'  2) with vividusVersion = '0.2.14-SNAPSHOT'

**story:** 

Meta:
@HyperWallet

Lifecycle:
Examples:
/tables/${locale}/HW.table

Scenario: [1] uplo
When I initialize the STORY variable `AffLocale` with value `<AffLocale>`
When I initialize the story variable `start-time` with value `#{generateDate(-PT2H)}`
When I initialize the story variable `filename` with value `AddFundNotExistingABO2021_01_20T12_18_49`
Given I am on a page with the URL 'https://neprivet.ru/'
When I scroll to the end of the page
When I take a screenshot

**Actual result:** step "When I scroll to the end of the page" is not passed (Step is not implemented)
**Expected result:** Step passed successful and further steps passed as well
[scrollPage.zip](https://github.com/vividus-framework/vividus/files/5843676/scrollPage.zip)

**Comment by valfirst** [comment]
The step as deprecated in [`0.2.1`](https://github.com/vividus-framework/vividus/releases/tag/release-0.2.1) and removed in `0.3.0`. Use replacement:
```
When I scroll context to $scrollDirection edge
```
