### ISSUE TITLE
The framework hasn't step for horizontal page scrolling

### ISSUE THREAD

**Issue by AnastasiyaKlenitskaya** [vividus-framework/vividus#140]
Problem: the framework hasn't step for horizontal page scrolling.

Our application requires horizontal scrolling of the page, so as the user scrolls the page horizontally, the data continues to be loaded. Accordingly, to make sure that all the data has arrived and there are no differences between the attributes (columns) in the database and the application, you need to scroll horizontally on the page, only after that you can clearly judge that all the data has arrived and the page is loaded without visible modal windows with errors.
In our application, the scroll looks like this:
![2019-11-01 14_43_26-Window](https://user-images.githubusercontent.com/57256259/68022759-4b5acc80-fcb6-11e9-959c-7d4f16ac9238.png)

Could you please add this step in Framework,
Kindly regards

**Comment by AnastasiyaKlenitskaya** [comment]
Could you please reopen this issue because it doesn't work.
I have tried two steps:
`When I scroll context to RIGHT edge`  
`When I scroll context to LEFT edge`
Both these steps failed with error:

> 2020-03-16 18:39:47,310 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingStoryReporter - When I scroll context to RIGHT edge (FAILED)
(java.lang.UnsupportedOperationException: Horizontal scroll of the page not supported)
2020-03-16 18:39:47,310 [batch-1-thread-1] ERROR org.vividus.bdd.log.LoggingStoryReporter - Step is failed with exception

[log4.log](https://github.com/vividus-framework/vividus/files/4339019/log4.log)

**Comment by AnastasiyaKlenitskaya** [comment]
Could you please close this issue. 
All work as needed.

**Comment by ikalinin1** [comment]
Closed per Anastasiya comment
