### ISSUE TITLE
Add functionality for Vividus as a part of container-based CI/CD

### ISSUE THREAD

**Issue by yanavera** [vividus-framework/vividus#1422]
Hi,

Some details on how we want to run automatic tests for Age Gate.

Test definitions are stored in the project’s git repo under /tests directory.
In .gitlab-ci.yml we have a “Auto Tests” job which run Vividus Docker image (built by Vividus team, can be hosted by Vividus team or in our project’s ECR) and passes /tests directory as a parameter. Vividus container then runs the tests and exit with code 0 (success) or non-zero (Gitlab CI will fail the pipeline and attach test reports output by Vividus to the container’s ephemeral filesystem).

The only caveat is that we use Gitlab CI with Kubernetes executor. This executor always overrides Docker image’s ENTRYPOINT with shell (see bug https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4125). Which means we need to have a way to kick in Vividus binary from this shell.
For example, we have a container which runs Jenkins jobs via API. This container has python as the entrypoint, so from the command line we can run it like this (parameters passed as CMD just like any other normal Docker image):

docker run -it trigger_jenkins_build:latest <JOB_NAME> --params "param1=value,param2=value" 

But from Gitlab CI we have to run it like this (notice we have to implicitly call python3 to run the script):

trigger jenkins build:
  stage: deploy
  image: $TRIGGER_JENKINS_BUILD
  script:
    - >
     python3 /trigger_jenkins_build.py <JOB_NAME>
     --params "param1=value,param2=value"
     --auth-file /etc/jenkins-credentials/dev.yaml

Back to Vivuds, it could be something similar:

Auto tests:
  stage: test
  image: $VIVIDUS_IMAGE
  script:
     - java -jar vividus.jar –test-dir=/tests
     
Feel free to contact  [Gennadii Aleksandrov ](mailto:Gennadii_Aleksandrov@epam.com) more details

**Comment by gevial** [comment]
Please feel free to ping me for clarifications and testing in our GitLab CI.

**Comment by valfirst** [comment]
@gevial @yanavera 
Docker image has been built and pushed to Docker Hub: https://hub.docker.com/r/vividus/vividus/tags

Here is a short example how to run the tests:
1. There is a test project (e.g. https://github.com/vividus-framework/vividus-starter)
1. `cd vividus-starter`
1. `mkdir results` - this folder is going to be used to store test logs and reports, it's not required to create a new folder, any existing folder at any location can be used
1. `docker run --rm --mount source="$(pwd)/src/main/resources",target=/vividus/resources,type=bind --mount source="$(pwd)/results",target=/vividus/output,type=bind vividus/vividus:0.3.1-SNAPSHOT`
1. Find the test execution artifacts in `results` folder

NOTE: please, bear in mind the docker image includes only java runtime and doesn't contain any browsers, so if you want to run web UI tests, it's recommended to use Selenium Grid

**Comment by gevial** [comment]
Thanks @valfirst ! Can confirm everything is working as expected. Well done!
