### ISSUE TITLE
Add Azure blob storage v2 support

### ISSUE THREAD

**Issue by alex-aladin-a** [vividus-framework/vividus#1460]
Features needed:
1) connect to Azure blob storage
2) list files based on provided initial path
	- with recursive = 'Yes' option to list files in subfolders
	- with recursive = 'No' option to list files in initial folder only
3) filtering feature for listing files:
	- based on file name (+ partial match)
	- based on file name mask
	- based on file extension
	- based on file creation date (<, <=, =, >, => some specific date passed as a parameter)
	- based on file modification date 
	- based on file size
	- based on any combination of above items
4) open file and read the content
5) download a file/folder
6) upload a file/folder

**Comment by valfirst** [comment]
@alex-aladin-a please checkout a new plugin released in [0.3.4](https://github.com/vividus-framework/vividus/releases/tag/release-0.3.4): https://docs.vividus.dev/vividus/0.3.4/plugins/plugin-azure-storage-account.html. It covers many of the requested operations, but not all of them. Feel free to reopen this ticket in case if the required functionality is missed.
