### ISSUE TITLE
Invalid JSON created when a User runs tests

### ISSUE THREAD

**Issue by ST-2017** [vividus-framework/vividus#1477]
**Describe the bug**
"_<JSON_files_path> does not contain needed JSON files_" message appears in Terminal when a User tries exporting tests with XRay
[InvalidJSON.txt](https://github.com/vividus-framework/vividus/files/6075584/InvalidJSON.txt)

**To Reproduce**
Run any test and check the created .json file
```
Scenario: Invalid JSON

!-- Step 1
!-- Step 2
!-- Step 3
```

**Expected behavior**
JSON file has a valid form to export tests

**Execution environment (please complete the following information):**
 - Vividus version: 0.3.1

**Comment by ST-2017** [comment]
Priority - 1

**Comment by valfirst** [comment]
Fixed by #1512
