### ISSUE TITLE
Accessing Shadow DOM elements

### ISSUE THREAD

**Issue by andrei-mask** [vividus-framework/vividus#1494]
**Description**
There in not any possibility to interact with web-elements located under shadow-DOM element.

**Comment by valfirst** [comment]
https://github.com/SeleniumHQ/selenium/commit/e1d15c49e22752bbd0ff06cd9f98c2216169e9e2#diff-38a0963a6364b09ad867aa9a66c6d009673c21e182015461da236ec361877f77 - it makes sense to consider as well
