### ISSUE TITLE
Investagate the possibility to use nested FILTERING transformer

### ISSUE THREAD

**Issue by cherevachy** [vividus-framework/vividus#1544]
The use case behind this request is to store several sets of data under one and the same table, e.g.:
promotional.table:
{transformer=FROM_LANDSCAPE}
|innovationTypeIdVar    |Trend              |Brend|
|productLineCodeVar     |(D) Dazzling (024) |025|
|priorityCodeVar        |Medium             |Light|
|majorInventoryTypeIdVar|Promotional (120)  |121|
|inventoryTypeIdVar     |Gifts (32)         |33|
|promotionTypeIdVar     |Holiday (110)      |111|
|durationVar            |6                  |7|
|majorCategoryIdVar     |Makeup (510)       |511|
|applicationIdVar       |Eyes (15)          |16|
|categoryIdVar          |Eye Liners (17)    |18|
|subCategoryIdVar       |Gel Eye Liners (M9)|M10|
|programHealthIdVar     |Needs Attention    |On Track|
|guidanceVar            |10                 |11|

and later select specific data set from such table using FILTERING transformer nested into MERGING, snth like:
{
 transformer=MERGING,
 mergeMode=columns,
 fillerValue=null,
 tables=
  \{
    transformer=FILTERING\,
    byRowIndexes=1
  \}
  tables/promotional.table;
  tables/regression.table
}

At the moment the script is not selecting byRowIndex 1

**Comment by cherevachy** [comment]
Sample tables:
tables/promotional.table - 
{transformer=FROM_LANDSCAPE}
|innovationTypeIdVar        |Trend                      |trend|
|productLineCodeVar       |(D) Dazzling (024) |024  |
|majorInventoryTypeIdVar|Promotional (120)  |120   |

tables/regression.table - 
{transformer=FROM_LANDSCAPE}
|tokenExpiration             |#{toEpochSecond(#{generateDate(PT5H, yyyy-MM-dd'T'HH:mm:ss)})}|
|programNameVar              |vividus-auto-#{generate(Number.digits '5')}                   |

expected result of filtering by byRowIndex 0 & merging - 
{transformer=FROM_LANDSCAPE}
|innovationTypeIdVar          |Trend                      |
|productLineCodeVar         |(D) Dazzling (024) |
|majorInventoryTypeIdVar  |Promotional (120)  |
|tokenExpiration                 |#{toEpochSecond(#{generateDate(PT5H, yyyy-MM-dd'T'HH:mm:ss)})}|
|programNameVar              |vividus-auto-#{generate(Number.digits '5')}                   |

expected result of filtering by byRowIndex 1 & merging - 
{transformer=FROM_LANDSCAPE}
|innovationTypeIdVar         |trend|
|productLineCodeVar         |024  |
|majorInventoryTypeIdVar  |120   |
|tokenExpiration                 |#{toEpochSecond(#{generateDate(PT5H, yyyy-MM-dd'T'HH:mm:ss)})}|
|programNameVar              |vividus-auto-#{generate(Number.digits '5')}                   |

**Comment by ikalinin1** [comment]
```shell
{
  transformer=MERGING,
  mergeMode=columns,
  fillerValue=null,
  tables=
    \{transformer=FROM_LANDSCAPE\}
    \{transformer=FILTERING\, byRowIndexes=1\}
    data/tables/first.table;
    data/tables/second.table
}
```

This is the correct way to use transformers.

When the table is loaded transformer that exists within the table file will be executed after the transformer described before table file reference (it is expected behavior).

In your particular case, the table loaded from the file was filtered by row index and then transformed from the landscape.
