### ISSUE TITLE
Consider adding support of global variables & expression to .ftl templates

### ISSUE THREAD

**Issue by cherevachy** [vividus-framework/vividus#1545]
At the moment if a user want to add a global variable to the template, he needs to pass it through the actual step that uses the template, e.g.:
```
Given I initialize the SCENARIO variable `createProgramPOST` using template `/templates/createProgramPOST.ftl` with parameters:
{transformer=MERGING, mergeMode=columns, tables=tables/regression.table;tables/promotional_api.table}
|userRole1Name         |
|${estee_gpm_user_name}|
```
It would be nice if the user could just paste the global variable directly into the .ftl file.

The same thing with the VIVIDUS expressions - they are currentl not accepted in .ftl file and the user have to pass them through the steps or look for FreeMarker alternatives which breaks the integrity of the scripts.

**Comment by uarlouski** [comment]
See https://docs.vividus.dev/vividus/latest/commons/vividus-steps.html#_initialize_variable_using_template for details
