### ISSUE TITLE
Stories are randomly run and included in the Allure test report

### ISSUE THREAD

**Issue by ST-2017** [vividus-framework/vividus#1615]
**Describe the bug**
Not all stories are run and included in the test report. In addition to this, excluded stories can be in the report after the next run.

**To Reproduce**
Run a batch of stories.

**Expected behavior**
All stories run and included in the Allure report.

**Artifacts**
[Stack-trace.txt](https://github.com/vividus-framework/vividus/files/6440284/Stack-trace.txt)

**Execution environment (please complete the following information):**
 - Vividus version: 0.3.6-SNAPSHOT
 - OS: macOS

**Comment by ikalinin1** [comment]
@ST-2017  Please provide story example which is not reported

**Comment by ST-2017** [comment]
[CESavedCocktailsPage.txt](https://github.com/vividus-framework/vividus/files/6440412/CESavedCocktailsPage.txt)
Please note: this story was excluded the first time but included after the next run.

**Comment by valfirst** [comment]
The root cause is https://jbehave.atlassian.net/browse/JBEHAVE-1486
