### ISSUE TITLE
Files Checksum calculation

### ISSUE THREAD

**Issue by alex-aladin-a** [vividus-framework/vividus#1647]
I have a following test scenario:
1) having a file I upload it to Azure blob
2) an Application under test copies file from one folder to another (from one storage account to another)
3) then I need to make sure target file is not corrupted and matches the source file

To do that I need vividus to calculate file checksum, that can be used to compare files.
I would be nice to have an algorithm as an input parameter e.g. (MD5, SHA):
When I calculate 'filePath/fileName' file checksum using 'algorithm' algorithm
If not lets use MD5

**Comment by nadinsav** [comment]
I need to have ability to convert email to sha1 format
