### ISSUE TITLE
Add possibility to run SQL-like queries for CSV

### ISSUE THREAD

**Issue by dzmitryfdanone** [vividus-framework/vividus#1655]
User should be able to run SQL-like stories for CSV in order to:
1) To convert column type (ex. from string to Big Decimal)
2) To round values (ex. DB returns 1.11 value and 1.111 is located in CSV for same value). We need to successfully compare such values.

**Comment by valfirst** [comment]
Relates https://github.com/simoc/csvjdbc/issues/39, https://github.com/simoc/csvjdbc/issues/42
