### ISSUE TITLE
Add possibility to perform visual checks on mobile devices

### ISSUE THREAD

**Issue by Romashkinet** [vividus-framework/vividus#1686]
As a user I want to be able to perform visual checks on mobile devices (mobile phones & tablets):
 - gather baseline
 - compare baseline screen with target screen
 - choose level of comparison (e.g. pixel to pixel, layout etc.)

**Comment by NatalliaSamarava** [comment]
+ Add possibility to perform visual check on mobile device for FULL screen.

**Comment by valfirst** [comment]
The implementation of full-screen screenshots is tracked in #2005
