### ISSUE TITLE
Custom allure output location

### ISSUE THREAD

**Issue by cherryxiangyi** [vividus-framework/vividus#1703]
My drive C always and almost full and the defaulted allure report always goes to user's directory

**Describe the solution you'd like**
I suggest the overriding.properties can have extra properties => **bdd.batch-1.allureReport.location**= , so that i can specific the location of allure report

**Describe alternatives you've considered**
Nope. I can't run if my C drive almost full

**Additional context**
N/A

**Comment by valfirst** [comment]
@cherryxiangyi try to use the following property to change the output location:
```properties
output.directory=D:\my\folder\for\tests\output
```

**Comment by valfirst** [comment]
@cherryxiangyi please feel free to reopen this issue if any other details are required or the provided solution doesn't work for you
