### ISSUE TITLE
Hardcoded chromium version from profile.properties isn't overridden if it is set on profile level in tests 

### ISSUE THREAD

**Issue by NadzeyaDunayeva** [vividus-framework/vividus#1726]
**Describe the bug**
There is hardcoded version of chromium in https://github.com/vividus-framework/vividus/blob/master/vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/edge/chromium/profile.properties
It isn't overridden by new value in environment.properties on profile level in tests
Example:
https://github.com/vividus-framework/vividus/blob/master/vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/edge/chromium/profile.properties
selenium.grid.capabilities.browserVersion=80

src/main/resources/properties/profile/web/desktop/edge/chromium/environment.properties
selenium.grid.capabilities.browserVersion=90

**To Reproduce**
1. Add environment.properties for Chromium profile
2. set there browserVersion that differs from vividus default, like selenium.grid.capabilities.browserVersion=90
3. run some UI test using chromium
configuration.profiles=web/desktop/edge/chromium

Scenario: google
Given I am on a page with the URL 'https://www.google.com/'

**Expected behavior**
chromium version set in tests is used, like 90

**Artifacts**
[Override Chromium version.log](https://github.com/vividus-framework/vividus/files/6662014/Override.Chromium.version.log)

**Execution environment (please complete the following information):**
vividus 0.3.6-SNAPSHOT

**Desktop Web (if applicable, please complete the following information):**
 - OS: Windows 10
 - Browser chromium
 - Version 90

**Comment by ikalinin1** [comment]
@NadzeyaDunayeva 
1. This is not recommended to try override existing profile behavior by adding your own by the same path because we do not guarantee which one will last, so it may lead to instability.
2. We recommend creating a custom profile instead if it is necessary
3. We will remove the hardcoded version in milestone 0.4.0
