### ISSUE TITLE
Add steps to capture/validate performance metrics for native iOS Apps

### ISSUE THREAD

**Issue by GrimA9e** [vividus-framework/vividus#1789]
**As a** framework user
**I want to** capture and validate performance metrics for iOS application
**So that** I can automatically assess its performance under different conditions 

Basing on the initial investigation it seems Appium supports a set of Apple built-in analyses and measurements, i.e. https://appiumpro.com/editions/12-capturing-performance-data-for-native-ios-apps. Thus new steps are needed to gather and analyse obtained data, e.g.:
- When I start gathering performance metrics:
|metricName1|metricName2|
- When I stop gathering performance metrics
- Then `$function($metricName)` is $comparisonRule `$quantity` ($function should support standard set like AVG, MIN, MAX)

**Comment by ikalinin1** [comment]
http://jamie-wong.com/post/reverse-engineering-instruments-file-format/

**Comment by valfirst** [comment]
Due to the binary nature of the recorded data, the analysis can be performed using only native utils, thus the validation of the recorded results won't be implemented in scope of this ticket.
