### ISSUE TITLE
Add step to check right and left swipes

### ISSUE THREAD

**Issue by YulyaBratishcheva** [vividus-framework/vividus#1796]
Please either **extend** existing step _When I swipe direction to element located `locator` with duration swipeDuration by_ adding right and left swipes or **add** a new step for **right and left swipe**

**Comment by NadzeyaShkliarevich** [comment]
Please add this functionality since we need to swipe to the right/left elements in carousel

**Comment by valfirst** [comment]
The original feature request will be addressed by #1930. The request for the swipe in carousel from the above comment will be tracked in a separate ticket: #1933
