### ISSUE TITLE
Add functionality of drag & drop for mobile app

### ISSUE THREAD

**Issue by NadzeyaShkliarevich** [vividus-framework/vividus#1808]
We need to have possibility to drag & drop elements on the screen. Please add corresponding step.

https://user-images.githubusercontent.com/61141379/126762869-cf0df316-b768-4bee-993a-4114945b4df4.mov

https://user-images.githubusercontent.com/61141379/130208607-303ed86e-25c2-41f8-8a2c-e79e8994879d.mov

**Comment by ZafarMaksudov** [comment]
For second video (drag.drop2.mov), we need to slide this black circle locator to LEFT or RIGHT side for particular time (e.g. PT1S). Meanwhile, we don't have exact locator as destination to slide it. We expect that this function will operate as **swipe method**, but starting point with exact locator to particular sideway.

**Comment by valfirst** [comment]
New step:
```gherkin
When I execute sequence of touch actions: $actions
```
where allowed actions types are:
- TAP
- TAP_AND_HOLD
- MOVE_TO
- MOVE_BY_OFFSET
- RELEASE
- WAIT
