### ISSUE TITLE
Variables are not resolved while table cartesian product creation

### ISSUE THREAD

**Issue by VolhaPrachkina** [vividus-framework/vividus#1847]
**Describe the bug**
I want to combine 2 tables and use a new table in the test run. There are variables in tables' names. A common table is uploaded earlier than variables are resolved 

**To Reproduce**
STR:
1. Use in the story: `Lifecycle:
Examples:
{transformer=CARTESIAN_PRODUCT, tables=story/smoke/table/${useCaseName}/DatabricksAnalytical.table;story/smoke/table/${useCaseName}/DatabricksWorkspaces.table}`

2. Use in the properties: `bdd.variables.global.useCaseName=qualityuc`

**Expected behavior**
A new table should be created for the run, the story should be run successfully

**Artifacts**
If applicable, add artifacts to help explain your problem:
 - [log.txt](https://github.com/vividus-framework/vividus/files/6917215/log.txt)

**Execution environment (please complete the following information):**
 - Vividus version: '0.3.7'
 - OS: win 10 Enterprise v.1909. OS build: 18363.1679
 - Java: 11.0.10

**Comment by valfirst** [comment]
The variables syntax must be escaped:
```gherkin
Lifecycle: Examples: {transformer=CARTESIAN_PRODUCT, tables=story/smoke/table/$\{useCaseName\}/DatabricksAnalytical.table;story/smoke/table/$\{useCaseName\}/DatabricksWorkspaces.table}
```

**Comment by valfirst** [comment]
The documentation is updated to address this case
