### ISSUE TITLE
Add steps to check Session storage 

### ISSUE THREAD

**Issue by YulyaBratishcheva** [vividus-framework/vividus#1876]
Please add functionality to check Session storage

**Comment by VerkhovtsovPavel** [comment]
@YulyaBratishcheva  Hello Yulya! Could you clarify which functionality is necessary for your checks, please? (e.g. presents of key in storage, value getting, value setting,  etc.)

**Comment by YulyaBratishcheva** [comment]
Hi @VerkhovtsovPavel  I need to check presence of token in Session storage and saving value of token in Session storage
