### ISSUE TITLE
It is impossible to make a visual check for mobile with current context

### ISSUE THREAD

**Issue by NadzeyaShkliarevich** [vividus-framework/vividus#1882]
![image](https://user-images.githubusercontent.com/61141379/129729396-41fbf1dc-ab70-4697-861a-c016bc45fdd5.png)

 vividusVersion = '0.3.8-SNAPSHOT', xcode Version 12.5.1, appium version 1.20.2

**Comment by valfirst** [comment]
Relates #1686
