### ISSUE TITLE
[known-issues] Add possibility to specify comment alongside with the known issue

### ISSUE THREAD

**Issue by ikalinin1** [vividus-framework/vividus#2011]
**Is your feature request related to a problem? Please describe.**
Currently, there is no possibility to put any information like a comment or additional details for the known issue. We. could communicate using the Jira ticket that is for sure, but it doesn't cover the case when you need to put some info along the known issue, so it may be seen in the report

**Describe the solution you'd like**
Add optional "comment"

```json

"VVD-1": {
    "type": "Internal",
    "assertionPattern": ".*Doctor Who.*",
    "scenarioPattern": "Verify step Then I verify assertions matching '.+'",
    "storyPattern": "AssertStepsTests",
    "comment": "With the help of the known we issue we verify functionality x"
  }

```
And allure
```
1) Known issue: VVD-1 (Type: INTERNAL. Status: UNKNOWN, Comment: With the help of the known we issue we verify functionality x). Number of elements found by ' Accessibility Id: 'Login'; Visibility: VISIBLE;' is equal to 1 [Expected: number of elements is a value equal to <1> Actual: <0>]
```

**Describe alternatives you've considered**
We could use the identifier as a workaround but it looks ugly

**Comment by valfirst** [comment]
Proposals:
1. `comment` -> `description`
2. `1) Known issue: VVD-1 - With the help of the known we issue we verify functionality x (Type: INTERNAL. Status: UNKNOWN). Number of elements found by ' Accessibility Id: 'Login'; Visibility: VISIBLE;' is equal to 1 [Expected: number of elements is a value equal to <1> Actual: <0>]`
