### ISSUE TITLE
VIVIDUS to ADO integration: fix 'Download Exporter JAR' link 

### ISSUE THREAD

**Issue by Aliaksei-Daroshchanka** [vividus-framework/vividus#2071]
ADO exporter documentation have a broken link for exporter JAR download
https://docs.vividus.dev/vividus/latest/integrations/azure-devops-exporter.html

The link currently leads to https://vividuscentral.jfrog.io/ui/native/snapshots/org/vividus/vividus-to-azure-devops-exporter/0.3.10-SNAPSHOT/vividus-to-azure-devops-exporter-0.3.10-SNAPSHOT.jar

When trying to download the file following error is shown:
```
{
  "errors": [
    {
      "status": 404,
      "message": "children items not found on all virtual repos"
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/64959478/136976196-49da0a01-57cf-46f9-8a40-a2f247e66bde.png)

**Comment by valfirst** [comment]
Duplicates #2019
