### ISSUE TITLE
Drag and drop step doesn't work on Material UI d'n'd elements

### ISSUE THREAD

**Issue by VolhaHoman** [vividus-framework/vividus#209]
Description:
An element is not shifted during the step: 
**When I drag element located `$origin` and drop it at $location of element 
 located `$target`**

STR:
```
Given I am on a page with the URL 'https://codesandbox.io/s/4qp6vjp319?from-embed'
When I wait until element located `By.xpath(//div[@id='csb-devtools'])` appears
When I take a screenshot
When I switch to a frame by the xpath '//iframe[contains(@sandbox,'allow-same-origin')]'
When I change context to an element by By.xpath(//div[@id='root']/ul)
When I drag element located `By.xpath(//span[text()='item 0'])` and drop it at BOTTOM of element located `By.xpath(//span[text()='item 4'])`
```

**Expected behavior**
An element is shifted to the target place.

**Artifacts**
If applicable, add artifacts to help explain your problem:
 - Screenshots
 - Allure report
![Before_DrADr](https://user-images.githubusercontent.com/54664070/70330613-f1b66680-184e-11ea-98f9-1ee8dd729c8b.png)
![After_DrADr](https://user-images.githubusercontent.com/54664070/70330618-f3802a00-184e-11ea-9bcd-c9bc25dc3277.png)
[DragAndDrop_allure.zip](https://github.com/vividus-framework/vividus/files/3932665/DragAndDrop_allure.zip)

**Report**
Logs
[logs.txt](https://github.com/vividus-framework/vividus/files/3932683/logs.txt)

**Execution environment (please complete the following information):**
 - Vividus version: [e.g. 0.1.0]
 - OS: [Microsoft Windows 10 Enterprise]
 - jdk-12.0.2

**Desktop Web (if applicable, please complete the following information):**
 - OS: [ Windows 10]
 - Browser [chrome]
 - Version [78.0.3904.108 (Official Build) (64-bit)]

**Additional context**

**Comment by valfirst** [comment]
Some notes:
- it's required to refer draggable elements to make D&D accurate (e.g. for this particular case `By.xpath(//li[contains(., 'item 0')])` should be used)
- while re-ordering dynamic lists `bottom` coordinates of one element might become actual `bottom` of another element
