### ISSUE TITLE
Expand the step: 'When I execute the sequence of actions: $actions'

### ISSUE THREAD

**Issue by VolhaHoman** [vividus-framework/vividus#217]
**Description of actions**
A value is entered into the field, then appears a context menu and the value from the menu is chosen by a click.

**Step**
When I execute the sequence of actions:

|type                         |searchAttributes                                                |offset|
|CLICK_AND_HOLD  |By.xpath(//div)                                                   |(0, 0)|

**Please add to this step additional actions:**
- SEND_KEYS
- CLICK

**Comment by uarlouski** [comment]
https://github.com/vividus-framework/vividus/releases/tag/release-0.2.0-alpha
