### ISSUE TITLE
Unable to use example table key with space

### ISSUE THREAD

**Issue by uarlouski** [vividus-framework/vividus#2255]
**Describe the bug** 
Example table keys containing spaces are not resolved in scenarios

**To Reproduce**
```
Scenario: Resolve key with space
Then `<my key>` is equal to `e0edf9`
Examples:
|my key|
|e0edf9|
```

**Expected behavior**
The mentioned above scenario is passed

**Artifacts**
Allure report: 
[allure.zip](https://github.com/vividus-framework/vividus/files/7625699/allure.zip)

**Execution environment (please complete the following information):**
 - Vividus version: 0.4.0-SNAPSHOT

**Comment by valfirst** [comment]
Fixed by https://github.com/jbehave/jbehave-core/pull/15
