### ISSUE TITLE
"failStoryFast" affects stories that are not in known-issue pattern

### ISSUE THREAD

**Issue by Aliaksei-Andreyeu** [vividus-framework/vividus#2276]
**Describe the bug**
Given two known issues:
1. Known issue has "failStoryFast" set in "true" (1)
2. Known issue without "failStoryFast" element (2)

The essence: 
When a given known issue(1) was found during the test execution, and after that, _**another**_ known issue (2) was found, the following scenarios will be skipped, even though the second known issue (2) doesn't provide such behavior. 

**To Reproduce**
1. Create two known issues, with and without "failStoryFast" element.
2. Create several stories:

- the first contains known issue (with failStoryFast enabled)
- the second with multiple scenarios (the first scenario should contain known issue with failStoryFast disabled)

3. Make sure test will detect known issue with "failStoryFast" enabled **_firstly_**.
4. Run tests

**Expected behavior**
1. The first story runs;
2. The first known issue is found and fails the story;
3. The first scenario of the second story runs;
4. The second known issue is found, test execution continues;
5. The second scenario of the second story runs;

**Actual behavior**
1.
...
**_5. The second scenario did not started:_**

> "Step is not performed"

**Artifacts**
 - [Allure Report](https://github.com/vividus-framework/vividus/files/7685217/failFastIssue_Allure.zip)
 - [src directory of example project](https://github.com/vividus-framework/vividus/files/7685229/src.zip)

**Execution environment :**
 - Vividus version: 0.4.0-SNAPSHOT
 - OS: macOS Big Sur 11.5.2]
 - Java: Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

**Additional context**

- If the stories are separated into different batches, the issue is not reproduced
- settings the second known issue with "failStoryFast": false does not resolve the problem

**Comment by valfirst** [comment]
Fixed by https://github.com/jbehave/jbehave-core/pull/18
