### ISSUE TITLE
"failStoryFast" results to show stories/scenarios as 'broken' instead of 'known' in the console output final execution statistics 

### ISSUE THREAD

**Issue by Aliaksei-Daroshchanka** [vividus-framework/vividus#2298]
**To Reproduce**
1. Create a story with a failing step that prevents further story execution, there have to be multiple steps after the failing steps (not 0 or 1 step)
2. Describe bug in known issues file with "failStoryFast" = true
3. Verify in allure report that failed step is correctly recognized as a known issue and remaining multiple steps in the scenario are skipped
4. Check execution statistics in the console log > most (but not all) stories and scenarios are set to "broken" instead of "known" 

**Expected behavior**
Console execution log should match allure report showing all scenarios and stories as "known" when only known issues were found even if "failStoryFast" was true and many steps were skipped in many scenarios 

**Artifacts**
![image](https://user-images.githubusercontent.com/64959478/146508024-f018b13c-0b76-4754-8ff1-f3b5a36fca2b.png)
![image](https://user-images.githubusercontent.com/64959478/146508136-03756386-81e5-4461-8ee3-f77bef9e8bb9.png)

**Execution environment (please complete the following information):**
 - Vividus version: 0.3.12
 - OS: Win10
 - Java: 15.0.2+7-27

**Comment by draker94** [comment]
@Aliaksei-Daroshchanka Can you give the reproduce details?
What specific steps are used (which described in known-issues especially)? 
And it would be great if you attached a Allure report with the problem suites.
