### ISSUE TITLE
Eliminate unnecessary information from applitools step execution log in allure

### ISSUE THREAD

**Issue by uarlouski** [vividus-framework/vividus#2464]
**Is your feature request related to a problem? Please describe.**
When executing applitools visual testing steps the execution log of step in allure report contains unnecessary information like requests to applitools and responses from it, so it looks like debug info for developers, not end users

**Attachments**
<img width="734" alt="Screenshot 2022-02-11 at 11 13 06" src="https://user-images.githubusercontent.com/30923336/153558483-163b32d9-d59c-48a0-a0f5-b9e67f55a7bf.png">

**Comment by valfirst** [comment]
Fixed by #2520, #2521
