### ISSUE TITLE
Data generator creates the same values for different variables

### ISSUE THREAD

**Issue by Aliaksei-Andreyeu** [vividus-framework/vividus#2600]
**Describe the bug**
When initialize several variables in a row using data generation, all values are duplicated.

**To Reproduce**
Set several variables using the same pattern, e.g.:
```
When I initialize the SCENARIO variable `variableName4` with value `#{generate(regexify '[A-Za-z0-9]{7}')}`
When I initialize the SCENARIO variable `variableName5` with value `#{generate(regexify '[A-Za-z0-9]{7}')}`
When I initialize the SCENARIO variable `variableName6` with value `#{generate(regexify '[A-Za-z0-9]{7}')}`
```
**Expected behavior**
3 different variables are created.

**Actual beharvior**
Values of all variables are equal

**Artifacts**
If applicable, add artifacts to help explain your problem:
- <details><summary>Screenshot</summary> <img width="378" alt="Screenshot 2022-03-21 at 16 41 29" src="https://user-images.githubusercontent.com/66934999/159273433-f1190acf-47e6-406b-999e-4a63a6f53164.png">
 - [Allure Report.zip](https://github.com/vividus-framework/vividus/files/8315873/dataGenerationAllure.zip)

**Execution environment (please complete the following information):**
 - Vividus version: 0.4.4-SNAPSHOT
 - OS: macOS Monterey 12.2.1
 - Java: 
 ```
java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```

**Comment by valfirst** [comment]
The issue was fixed by #2592. Please make sure you use the latest snapshot version: 
```sh
./gradlew clean build cleanEclipse eclipse --refresh-dependencies
```
