### ISSUE TITLE
Reusable locators omit everything after comma if it's not escaped

### ISSUE THREAD

**Issue by Aliaksei-Andreyeu** [vividus-framework/vividus#2802]
**Describe the bug**
In case part of the reusable locator contains comma and it was not escaped, this remainder of the locator would be omitted.

**To Reproduce**
1. Set up reusable locator;
2. Use comma and additional text after;
3. Run scenario with such locator;
e.g.:
```
Then number of elements found by `myLocator(Text before comma, text after comma)` is ｟=｠ `1`
```
**Expected behavior**
Locator is resolved completely (e.g. xpath //*[@name="Text before comma, text after comma"])

**Actual behaviour**
Part of the locator is thrown out (e.g. xpath //*[@name="Text before comma"])

**Execution environment (please complete the following information):**
 - Vividus version: 0.4.9

**Comment by valfirst** [comment]
why not to escape the comma: `\,` ?

**Comment by ikalinin1** [comment]
`why not to escape the comma: \, ?`
The data is dynamic and there is no single place where escape logic could suit, on the other hand escaping everywhere obsoletes usefulness of reusable locator

@valfirst As we discussed, we need to be aware of the number of parameters in the locator pattern and take them into account during locator creation
