### ISSUE TITLE
Incorrect baselines establishing for SM/MD layouts in case of context change

### ISSUE THREAD

**Issue by Sh-test** [vividus-framework/vividus#2833]
**Describe the bug**
For MD/SM layouts, established baselines are not correspond exactly to context chosen through xpath. 

**To Reproduce**
1) Login to web application with SM/MD layout
2) Open the page contains filters
3) Open the Filters tab
4) Change context to necessary area
5) Establish baseline. 
Note: Vividus story with exact steps to reproduce will be shared with automation engineer in personal

**Expected behavior**
The baseline exactly corresponds to area was chosen by xpath through 'change context' step. 

**Artifacts**
Expected result (highlighted by frame - taken manually)
![2022-06-01_18h18_51](https://user-images.githubusercontent.com/25951146/171826235-da7bec3c-7b66-4d10-884f-98e755ca6538.png)
Actual result (baseline taken with Vividus)
![All_Filter_SM](https://user-images.githubusercontent.com/25951146/171826378-79a40db8-51ff-4600-ade4-7de916c9ad2d.png)

**Execution environment (please complete the following information):**
 - Vividus version: 0.4.9
 - Java: JDK 18 

**Desktop Web (if applicable, please complete the following information):**
 - OS: WIN 10 PRO build 19044.1706
 - Browser Chrome
 - Version 102.0.5005.63 (Official Build) (64-bit)

**Additional context**
 Probably, it's a general issue for all web application in SM/MD layouts. 
 All specific project information and details will be shared with automation engineer in personal.

**Comment by valfirst** [comment]
@Sh-test we won't be able to help you without steps to reproduce

**Comment by Sh-test** [comment]
@valfirst we're trying to find a way to share project specific information with Vividus team according to our policies

**Comment by valfirst** [comment]
Please, reopen the ticket once the details are added
