### ISSUE TITLE
When I create file with content at path over SFTP does not display content of created file

### ISSUE THREAD

**Issue by MarynaBelskayaA** [vividus-framework/vividus#2843]
**Describe the bug**
Step ``` When I create file with content `$content` at path `$destination` on $server over SFTP``` does not display content of created file

![1-SFTP-no-file-content](https://user-images.githubusercontent.com/104360916/172579892-223b0abb-313e-4a39-9128-d930ed63144c.jpg)

**Comment by valfirst** [comment]
@MarynaBelskayaA , could you please elaborate:

1) why do you expect the result of `PUT` command to be a content of the file?
2) why is it an issue for you?

**Comment by MarynaBelskayaA** [comment]
Hi @valfirst.
Perhaps,
I do not clearly understand the purpose of **result** file under step definition.
I thought that the **result** file should contain content of created file. But **result** file is always empty.

Could you please clarify for me what **result** file is expected to contain?

**Comment by valfirst** [comment]
`result` is always empty for SFTP commands which don't provide any output. But it's not empty for commands like `ls`, `get`, `pwd`, etc.

**Comment by MarynaBelskayaA** [comment]
Thank you for clarification. I will close this ticket
