### ISSUE TITLE
Add possibility to send message in kafka topic with key

### ISSUE THREAD

**Issue by EkaterinaBulgakova** [vividus-framework/vividus#2915]
**Is your feature request related to a problem? Please describe.**
I'm and team members are always frustrated when we can only send kafka message using the step 'When I send data `$data` to `$producerKey` Kafka topic `$topic`' without key mentioned there. 
As the key is used by kafka to put data in a specific partition which is how kafka allows for large streams of data.
So developers asked to add possibility to send kafka message with key using vividus to process data correctly when auto tests are running.

**Describe the solution you'd like**
Add step that allows to send kafka message WITH key

**Describe alternatives you've considered**
Unfortunately I can't suggest alternative here :( 
Maybe we can specify partition instead of key, but I think that it's better to specify the key anyway 

**Additional context**
-

**Comment by Aliaksei-Andreyeu** [comment]
It would be very helpful to have that feature, please add it

**Comment by EKrysenko** [comment]
Could you please add it, will be soooooo nice of you guys!
