### ISSUE TITLE
Third party cookies are disabled for non-incognito when using selenium grid with standalone seleniarm/chromium container

### ISSUE THREAD

**Issue by Aliaksei-Daroshchanka** [vividus-framework/vividus#2944]
**Describe the bug**
When running tests using selenium grid with standalone seleniarm/chromium docker container browser inside of the container has setting to forbid all third party cookies

For both chrome and chromium installed to desktop default configuration is to forbid third-party cookies only in incognito, but the container browser has different defaults for some reason 

This interferes with some tests which in non-prod environment require third party cookies for authentication

--headless mode allows to work around the issue but is not convenient when debugging is required

**To Reproduce**
1) Run tests using selenium grid and following docker container seleniarm/standalone-chromium:latest
2) Use some wait in tests, while tests are waiting - connect to selenium grid session and check browser cookie settings

**Actual behavior**
Browser is set to not allow any third-party cookies 

**Expected behavior**
Third-party cookies should be allowed at least for non-incognito windows

**Artifacts**
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/64959478/178738744-fc8a02d2-4a58-47d1-8dd8-e9614b05f78a.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/64959478/178739298-760aa0ae-e105-4730-83a7-190e1db18982.png">
**Execution environment (please complete the following information):**
 - Vividus version: 0.4.6 & 0.4.12
 - OS: macOS 12.4 ARM
 - Java: 16.0.2+7-67

**Desktop Web (if applicable, please complete the following information):**
 - OS: latest seleniarm/chromium docker container
 - Browser: Chromium 
 - Version v.103.0.5060.53

**Additional context**
Solution using web driver configuration described here: https://stackoverflow.com/questions/48667852/how-to-change-allow-sites-to-save-and-read-cookie-data-recommended-and-or-bloc/67260066#67260066

Running docker container using following string: docker run -d -e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1080 -p 4444:4444 --shm-size=2g seleniarm/standalone-chromium:latest

**Comment by VolhaHurynovich** [comment]
Hi,
you can use 
`web.driver.CHROME.experimental-options={"prefs": {"profile": {"cookie_controls_mode": 2}}}`
in property file (information about it I'll add in vividus documentation)

**Comment by Aliaksei-Daroshchanka** [comment]
> Hi, you can use `web.driver.CHROME.experimental-options={"prefs": {"profile": {"cookie_controls_mode": 2}}}` in property file (information about it I'll add in vividus documentation)

Thanks, that helped
