### ISSUE TITLE
Add step to work with content of Excel files in API response

### ISSUE THREAD

**Issue by volha-barysiuk** [vividus-framework/vividus#298]
Please, add a step that will check API response contains excel file and will verify content of this file. The step should allow to specify particular cell or a range of cells and check the string inside it. It is also needed to switch between different excel sheets

**Suggested step wording:**
```gherkin
Then response contains excel sheet with index `$index` and records:
|cellsRange         |valueRegex   |
|A1                |Data         |
|B2                |\d{2}        |
|C4:C10            |             |
```

```gherkin
Then response contains excel sheet with name `$name` and records:
|cellsRange         |valueRegex   |
|A1                |Data         |
|B2                |\d{2}        |
|C4:C10            |             |
```

**Parameters to pass through step:**
- cellsRange - may be used for a single cell reference or as a reference to the entire range of cells
- valueRegex - regular expression to match

**Comment by uarlouski** [comment]
Version: 0.2.1-SNAPSHOT
Example: https://github.com/vividus-framework/vividus/blob/master/vividus-tests/src/main/resources/story/integration/ExcelSteps.story
