### ISSUE TITLE
'The 'v' is not allowed as a key' is displayed if argument  is 'CONTROL,v ' on step 'When I execute sequence of actions:' 

### ISSUE THREAD

**Issue by SniazhanaMarkevich** [vividus-framework/vividus#2992]
**Describe the bug**
'The 'v' is not allowed as a key' is displayed  on step 
When I execute sequence of actions:
|type                |argument      	 |	
|KEY_DOWN    |CONTROL,v      |
|KEY_UP           |CONTROL,v      |

**To Reproduce**
1. Run the story attached with step 
When I execute sequence of actions:
|type                |argument      	 |	
|KEY_DOWN    |CONTROL,v      |
|KEY_UP           |CONTROL,v      |
2. Open Allure report.

**Expected behavior**
The story completes and the step passes. Сopied text previously pasted

**Artifacts**
If applicable, add artifacts to help explain your problem:
 - Screenshots
 - 
![image](https://user-images.githubusercontent.com/92158570/180982685-d282ec15-3188-4b3e-8c06-4e0fdd8b9219.png)

 - Allure report
 
[allure.zip](https://github.com/vividus-framework/vividus/files/9188896/allure.zip)

**Execution environment (please complete the following information):**
 - Vividus version: [ 0.4.0]
 - OS: Windows 10 Pro 21H2
 - Java: OpenJDK 17.0.2

**Desktop Web (if applicable, please complete the following information):**
OS: Windows 10 Pro 21H2
Chrome
Version 103.0.5060.134

**Comment by valfirst** [comment]
@SniazhanaMarkevich the possible solution:
```gherkin
When I execute sequence of actions:
|type      |argument|
|KEY_DOWN  |CONTROL |
|PRESS_KEYS|v       |
|KEY_UP    |CONTROL |
```
