### ISSUE TITLE
Composite steps not working inside conditional steps

### ISSUE THREAD

**Issue by vinay-kabbe** [vividus-framework/vividus#3033]
When we create a conditional step and give a composite step inside it , the composite step does not get executed
------------------------------------------------------------------------
Sample story which gives error is as below 
-----------------------------------------------
Meta :

GivenStories:  /path/to/test.story

Scenario:
-------------------------------------------------------------
test.story

Meta:

Scenario: 1.login to the application
When the condition '`#{eval(${testBooleanValue} == true)}' is true I do
|step|
|composite step|

-------------------------------------------------------------------------
when we run the story the composite step does not get executed and is just printed on the console without any execution

**Artifacts**
If applicable, add artifacts to help explain your problem:
 - Screenshots
 - Allure report
 - Test execution logs

**Execution environment (please complete the following information):**
 - Vividus version: [e.g. 0.4.10]
 - OS: Windows 10
 - Java: java 18.0.1.1 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

**Comment by valfirst** [comment]
@vinay-kabbe most probably you're facing known issue: https://github.com/vividus-framework/vividus/issues/1746. In order to debug your case could you please describe how variable `${testBooleanValue}` is initialized?

**Comment by ikalinin1** [comment]
@vinay-kabbe  if your variable is true or false you can use it without eval
```
When the condition '${testBooleanValue}' is true I do
|step|
|composite step|
```

**Comment by vinay-kabbe** [comment]
> @vinay-kabbe most probably you're facing known issue: #1746. In order to debug your case could you please describe how variable `${testBooleanValue}` is initialized?

the variable testBooleanValue is initialized in the property file from where it is directly read into the story

**Comment by vinay-kabbe** [comment]
> @vinay-kabbe if your variable is true or false you can use it without eval
> 
> ```
> When the condition '${testBooleanValue}' is true I do
> |step|
> |composite step|
> ```

I tried doing this but no change in behaviour , it still does not execute the composite step

**Comment by valfirst** [comment]
> the variable testBooleanValue is initialized in the property file from where it is directly read into the story

@vinay-kabbe could you please provide your test execution logs and report, or create [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/)

**Comment by vinay-kabbe** [comment]
> > the variable testBooleanValue is initialized in the property file from where it is directly read into the story
> 
> @vinay-kabbe could you please provide your test execution logs and report, or create [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/)

I have created a short example using google which demonstrates the problem that I am facing. Please have a look at it , the composite step is not executed if it is inside a conditional step
[vividus-starter.zip](https://github.com/vividus-framework/vividus/files/9290702/vividus-starter.zip)
Below is the allure report for the story which I ran in the above project
[allure-report-for-google-scenario.zip](https://github.com/vividus-framework/vividus/files/9290749/allure-report-for-google-scenario.zip)

**Comment by valfirst** [comment]
@vinay-kabbe 
1) The original scenario has typo:
```gherkin
... '>>>`<<<#{eval(...
```
remove backtick ` and everything will work

2) The provided test project also has the same typos:
```gherkin
When the condition '`#{eval(${isEnteredText} == true)}`' is true I do
```

It must be either
```gherkin
When the condition '#{eval(${isEnteredText} == true)}' is true I do
```
or 
```gherkin
When the condition `#{eval(${isEnteredText} == true)}` is true I do
```

3) Also [Ivan's suggestion](https://github.com/vividus-framework/vividus/issues/3033#issuecomment-1208173779) works perfectly:
```gherkin
When the condition '${isEnteredText}' is true I do
|step|
|composite step|
```
