### ISSUE TITLE
Step "When I find comparisonRule 'number' elements by locator and for each element do stepsToExecute" fails to convert

### ISSUE THREAD

**Issue by UladzislauArlou** [vividus-framework/vividus#3204]
**Describe the bug**
Step "When I find comparisonRule 'number' elements by locator and for each element do stepsToExecute" fails to convert

**To Reproduce**
Run the story attached in .txt file

**Expected behavior**
Test passed

**Artifacts**
**Allure:** [Error.zip](https://github.com/vividus-framework/vividus/files/9654165/Error.zip)
**Story:** [Error.txt](https://github.com/vividus-framework/vividus/files/9654171/Error.txt)

**Execution environment (please complete the following information):**
 - Vividus version: 0.4.16
 - OS: Windows 10 Pro 21H2

**Desktop Web (if applicable, please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Browser Chrome
 - Version 105

**Additional context**
The step in the story is "When I find >= '0' elements by By.xpath(//input[@name="dobDay"]) and for each element do". Step works if commas near 0 will be changed to `0` despite wrong syntax

**Comment by valfirst** [comment]
Please, use composite steps instead of nested loops. For example:

**Error.story**
```gherkin
Scenario: test
Given I am on a page with the URL 'https://www.bacardi.com'
When I find >= `0` elements by `By.xpath(//iframe[@id='agegate'])` and for each element do
|step                                                                    |
|When I switch to frame located `By.xpath(//iframe[@id='agegate'])`      |
|When I enter date of birth if needed                                    |
|When I add `1989` to field located `By.xpath(//input[@name='dobYear'])` |
|When I click on element located `By.xpath(//button[@id="cookie-agree"])`|
|When I switch back to the page                                          |
```

**composite.steps**
```gherkin
Composite: When I enter date of birth if needed
When I find >= '0' elements by By.xpath(//input[@name="dobDay"]) and for each element do
|step                                                                  |
|When I add `14` to field located `By.xpath(//input[@name='dobDay'])`  |
|When I add `10` to field located `By.xpath(//input[@name='dobMonth'])`|
```

**Result:**
<img width="1001" alt="result" src="https://user-images.githubusercontent.com/5081226/196267817-b9da3416-a5be-4c21-8b39-36f7afec37e4.png">
