### ISSUE TITLE
Align syntax of steps in vividus-plugin-rest-api

### ISSUE THREAD

**Issue by uarlouski** [vividus-framework/vividus#3207]
**Module:** https://github.com/vividus-framework/vividus/tree/master/vividus-plugin-rest-api

**List of steps:**

- When I send HTTP $httpMethod to the relative URL '$relativeURL'
- Then the response does not contain body
- Then the response body $comparisonRule '$content'
- Then the response body $validationRule resource at '$resourcePath'
- Then the response code is $comparisonRule '$responseCode'
- Then the response time should be less than '$responseTimeThresholdMs' milliseconds
- Then response header '$httpHeaderName' contains attribute: $attributes
- Then the value of the response header '$httpHeaderName' $comparisonRule '$value'
- Then the number of the response headers with the name '$headerName' is $comparisonRule $value
- When I save response header '$httpHeaderName' value to $scopes variable '$variableName'
- When I save response body to the $scopes variable '$variableName'
- Then the connection is secured using $securityProtocol protocol
- When I send HTTP $httpMethod to the relative URL '$relativeURL'

**Comment by valfirst** [comment]
Fixed by #3220
