### ISSUE TITLE
Header is included into screenshot even if screenshot configuration is used

### ISSUE THREAD

**Issue by veranikaChyrun** [vividus-framework/vividus#331]
**Describe the bug**
Excluded area is included into screenshot even if configuration is applied

**To Reproduce**
Scenario: test
When I remove all cookies from the current domain
Given I am on a page with the URL '<siteURL>'
When I change context to an element with the attribute 'attribute'='value'
When I ESTABLISH baseline with `form` using screenshot configuration:
|webHeaderToCut|
|160                     |

**Actual Result**
Header is included
![image](https://user-images.githubusercontent.com/60783053/74821863-4d07d900-5315-11ea-8e7c-9891fcd08bb6.png)

**Comment by ikalinin1** [comment]
![image](https://user-images.githubusercontent.com/17816729/75461071-491e2b80-5993-11ea-9dcf-09fb3e36c214.png)

**Comment by ikalinin1** [comment]
Fix in 0.2.1-snapshot #346
