### ISSUE TITLE
[need help] Xray Exporter

### ISSUE THREAD

**Issue by karyna-lebiadzeuskaya** [vividus-framework/vividus#3372]
Hi, we are trying to configure exporting Vividus tests to Xray.
We are reading documentation but haven't managed to succeed for now. To be more precise, it's not clear where application.properties file should be located.
Thank you in advance for your help!

Best regards,
Karyna

**Comment by valfirst** [comment]
@karyna-lebiadzeuskaya please check the updated steps: https://docs.vividus.dev/vividus/latest/integrations/xray-exporter.html#_export

**Comment by valfirst** [comment]
@karyna-lebiadzeuskaya your configuration is missing the required property: `xray-exporter.project-key`
