### ISSUE TITLE
Property proxy.trust-all-servers doesn't work

### ISSUE THREAD

**Issue by veranikaChyrun** [vividus-framework/vividus#341]
**Describe the bug**
When I mark story with meta 'proxy' and try to run it, there is an error in browser 'Your connection is not private
Attackers might be trying to steal your information from www.se.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID'
and page is not opened

When I tried to put property proxy.trust-all-servers=true it didn't help - the same message was shown in browser

**To Reproduce**
1. Mark a story with proxy meta
2. Add property proxy.trust-all-servers=true into environment.properties
3. Run the story

**Expected behavior**
There should not be an error in browser, but page should be opened

**Execution environment (please complete the following information):**
 - Vividus version: 0.2.1-SNAPSHOT
 - OS: Win10
 - Java: JDK13

**Desktop Web (if applicable, please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by uarlouski** [comment]
Internal docs were updated accordingly
