### ISSUE TITLE
Add ability to manage iterations limit (EXECUTIONS_NUMBER_THRESHOLD) in executable steps

### ISSUE THREAD

**Issue by KaniushykAnastasiya** [vividus-framework/vividus#3828]
On the project there is case where steps should be iterated more than 1000 times, which is current threshold for "_When I execute steps while counter is comparisonRule `limit` with increment `increment` starting from `seed`:stepsToExecute_" step

Currently we need approximate threshold = 5000 and it should be enough, but in the future we might need more iterations.
So there are few solutions we came up with: 
1) Configurable property so everybody can put any number they might need
2) Simply increase the threshold for the step 

![image](https://user-images.githubusercontent.com/111198880/231706544-f11fd3f1-0e68-4c3b-8294-e7701bfce3c6.png)

**Comment by valfirst** [comment]
@KaniushykAnastasiya could you please elaborate which actions are needed to be performed 5k times?

**Comment by KaniushykAnastasiya** [comment]
> @KaniushykAnastasiya could you please elaborate which actions are needed to be performed 5k times?

There is JSON file with information about products (more than 1000). 
It is final JSON which has already been filtered by values, so it can't be divided anymore.
Data from all products is needed (e.g. we need to sum values extracted from each product in JSON to get final summarized data)

Depending on the chosen solution we can go two ways: 
1) If configurable property is selected - it is the easier way for project and any quantity can be used 
2) If solution mentioned above is not really possible and the only option is increasing hardcoded threshold, we can use different way of filtration which will require some effort for refactoring and in such case quantity of products will be up to 2000, but still more than current threshold

**Comment by valfirst** [comment]
> e.g. we need to sum values extracted from each product in JSON to get final summarized data

@KaniushykAnastasiya do you know you can use [`sum`](https://github.com/json-path/JsonPath/tree/master#functions) function for that purpose?

**Comment by KaniushykAnastasiya** [comment]
> > e.g. we need to sum values extracted from each product in JSON to get final summarized data
> 
> @KaniushykAnastasiya do you know you can use [`sum`](https://github.com/json-path/JsonPath/tree/master#functions) function for that purpose?

Yes. 
But to filter products we need to merge two JSONs e.g. 
`  [{
    "To Currency": "USD",
    "Key": "Value",
    ...
  }, 
  {
    "To Currency": "USD",
    "Key": "Value2",
    ...
  }]`

and 
`    [{
        "Key": "Value",
        "Brand": "145",
        ...
    },
    {
        "Key": "Value3",
        "Brand": "145",
        ...
    }]
`
 by common 'Key' field.  Only if there is some data in second JSON, values from products should be calculated in first one. 
 
For example we go through first JSON, take Key from it, then go to the second one. If: 
1) There is product with such key - calculate
2) There is no such product - ignore

**Comment by valfirst** [comment]
@KaniushykAnastasiya would you mind providing anonymized sample scenario/story to demo your problem? I still believe there are more effective ways to write the tests

**Comment by valfirst** [comment]
> @KaniushykAnastasiya would you mind providing anonymized sample scenario/story to demo your problem? I still believe there are more effective ways to write the tests

@KaniushykAnastasiya?

**Comment by KaniushykAnastasiya** [comment]
> > @KaniushykAnastasiya would you mind providing anonymized sample scenario/story to demo your problem? I still believe there are more effective ways to write the tests
> 
> @KaniushykAnastasiya?

Sorry for late answer
I'll create such scenario in the nearest future and send it to you
It will be great if there is better and easier way to write test

**Comment by KaniushykAnastasiya** [comment]
Hello, @valfirst 
In attached ZIP folder there are two *.json files with common Key
I need to calculate the sum for values from the first file, but only for those products that are present in the second one
[JSON.zip](https://github.com/vividus-framework/vividus/files/11336453/JSON.zip)

**Comment by valfirst** [comment]
> I need to calculate the sum for values from the first file, but only for those products that are present in the second one

@KaniushykAnastasiya what is expected sum for the provided data?

**Comment by valfirst** [comment]
@KaniushykAnastasiya the solution is super-simple:
```gherkin
Scenario: Test
When I save JSON element from `#{loadResource(data/SecondJSON.json)}` by JSON path `$..CommonKey` to scenario variable `keysToSum`
When I save JSON element from `#{loadResource(data/FirstJSON.json)}` by JSON path `$..[?(@.CommonKey in ${keysToSum})].ValueToCalculate.sum()` to scenario variable `sumOfValues`

```

**Comment by valfirst** [comment]
**Original solution**:
<br/>
<img width="1035" alt="Screenshot 2023-04-27 at 00 35 41" src="https://user-images.githubusercontent.com/5081226/234708639-4c4571c9-eef7-4e55-951c-ea81c3ac5f01.png">

<br/><br/><br/>
**Improved solution**:
<br/>
<img width="779" alt="Screenshot 2023-04-27 at 00 35 12" src="https://user-images.githubusercontent.com/5081226/234708657-570484d8-3c7b-44f4-b780-123776884978.png">

**Comment by KaniushykAnastasiya** [comment]
Sum is presented in another file and I'll compare the value after calculation
Didn't know about  `$..[?(@.CommonKey in ${keysToSum})]` option, I'll try to use it
Really looks like very simple solution, thank you so much for help
