### ISSUE TITLE
The Sauce VMs failed to start the browser or device. Infrastructure Error

### ISSUE THREAD

**Issue by VolhaHoman** [vividus-framework/vividus#409]
Usual run of a test on Vividus 0.2.2-SNAPSHOT in Firefox browser with SauceLabs enabled leads to an error: 
Infrastructure Error -- The Sauce VMs failed to start the browser or device.
For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 27.82 seconds
Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21'
System info: host: 'EPBYMINW0115', ip: '100.64.12.25', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.1'
Driver info: driver.version: RemoteWebDriver

**To Reproduce**
 Given I am on a page with the URL 'https://kb.epam.com/' 

**Expected behavior**
The page is loaded

**Artifacts**
[log4.log](https://github.com/vividus-framework/vividus/files/4356077/log4.log)

**Execution environment (please complete the following information):**
 - Vividus version: [0.2.2-SNAPSHOT]
 - OS: [Windows 10 Enterprise]
 - Java: [jdk-11.0.1]
 - SauceLabs logs:
[SauceLabs logs.txt](https://github.com/vividus-framework/vividus/files/4356091/SauceLabs.logs.txt)

**Desktop Web (if applicable, please complete the following information):**
 - OS: [Windows 10]
 - Browser [firefox]
 - Version [74]

**Comment by uarlouski** [comment]
Please use the following prefix for sauce labs desired capabilities
selenium.grid.capabilities.sauce\:options.<property>
For examples screenResolution should be specified as
selenium.grid.capabilities.sauce\:options.screenResolution=1920x1200
