### ISSUE TITLE
Add a mechanism for a random choice from predefined list

### ISSUE THREAD

**Issue by MaryiaTsyhanok** [vividus-framework/vividus#411]
**I need a mechanism that allows me to pick a random value from a predefined list.**
_Example:_
I have a list or predefined values: ['red', 'blue', 'yellow']. I expect to have expression/function _random.choice_ that will return one random value from the list:
```
choice_1 = random.choice(['red', 'blue', 'yellow'])
choice_1 >> 'red'
choice_2 = random.choice(['red', 'blue', 'yellow'])
choice_2 >> 'yellow'
```
This expression/function is expected to be used in scenarios and templates

**Comment by ikalinin1** [comment]
@MaryiaTsyhanok use this as
```java
 #{anyOf(1, 2, 3)} 
```
To escape comma please use `\`
```java
#{anyOf(1, 2\,3 ,4)}
