### ISSUE TITLE
The field in focus is not visible by version 0.2.2-snapshot in Firefox

### ISSUE THREAD

**Issue by VolhaHoman** [vividus-framework/vividus#421]
The field in focus is not visible for the Firefox while is visible for the Chrome, Edge and Safari.

**To Reproduce**
Given I am on a page with the URL 'https://kb.epam.com/'
When I enter `<testUser>` in field located `By.xpath(//input[@placeholder='user_name@epam.com'])` **or** (When I enter `<testUser>` in field located `By.name(UserName)`)

**Expected behavior**
<testUser> data is entered in the field

**Actual behavior**
<testUser> data is NOT entered in the field

**Artifacts**
[Doc1.docx](https://github.com/vividus-framework/vividus/files/4370725/Doc1.docx)

**Execution environment:**
- Vividus version: [0.2.2-SNAPSHOT]
- OS: [Windows 10 Enterprise]
- Java: [jdk-11.0.1]

**Desktop Web:**
- OS: [Windows 10]
- Browser [firefox]
- Version [74]

**Comment by Ulyana-Yeryksonava** [comment]
please, add a wait before typing text. for example like this:
Scenario: Verify step Then I verify assertions matching '$assertionsPattern'
Given I am on a page with the URL 'https://kb.epam.com/'
When I wait until element located `By.xpath(//input[@placeholder='user_name@epam.com'])` appears
When I enter `uuu@epam.com` in field located `By.xpath(//input[@placeholder='user_name@epam.com'])`
