### ISSUE TITLE
Issue in usage of @skip meta data

### ISSUE THREAD

**Issue by VolhaBarysuik** [vividus-framework/vividus#432]
**Describe the bug**
Parametrized scenarios with Examples table and all scenarios placed below are skipped from running and are excluded from Allure report until any from scenarios above contains @skip meta data

**To Reproduce**
```
Scenario: 0 - Test that is skipped
Meta: @skip
When I initialize the Scenario variable `varName` with value `value`

Scenario: 1 - Test without examples table
When I initialize the Scenario variable `varName` with value `value`

Scenario: 2 - Test with examples table
When I initialize the Scenario variable `<varName>` with value `<value>`
Examples:
|varName|value     |
|var1   |testValue1|

Scenario: 3 - Test coming after the one with examples table
When I initialize the Scenario variable `varName` with value `value`
```

**Expected behavior**
Only directly marked with @skip meta data scenarios should be excluded from test run, subsequent scenarios should not be affected

**Artifacts**
Please find test story and its allure report in archive attached
[Test Artifacts.zip](https://github.com/vividus-framework/vividus/files/4381773/Test.Artifacts.zip)

**Execution environment (please complete the following information):**

- Vividus version: 0.2.1
- Java: 12

**Comment by VolhaBarysuik** [comment]
Seems that the issue appears only for non UI tests and is caused by Eclipse configuration. The @skip meta works as expected if to start test through console by simple command `gradlew runStories`. Then all scenarios are included into the test run and can be reviewed in Allure report. Please check latest run of the same story through console attached [allure.zip](https://github.com/vividus-framework/vividus/files/4407457/allure.zip).
I've upgraded to java 13, updated Vividus build system to 0.2.2 and installed latest Eclipse version 2020-03 (4.15.0), but the issue still persists if to perform tests in Eclipse. 

Anyway the issue can be closed as there is a simple workaround as for running tests in console.

**Comment by valfirst** [comment]
Relates to #438

**Comment by MrsMarta** [comment]
I also faced @skip meta filter issue in Eclipse for UI tests described by Olga above. 
My configuration: vividus: 0.2.2-SNAPSHOT, Eclipse 2019-06 (4.12.0), build system 1.0. 
Even though the CLI run workaround is present, it is more convenient to use the familiar way to run tests in IDE, see JUnit runner progress visualized by scenarios and more readable logs during run. Hope it will be covered in #438 per comment above
