### ISSUE TITLE
List failed/broken tests after the execution statistics

### ISSUE THREAD

**Issue by lammaer** [vividus-framework/vividus#4438]
**Is your feature request related to a problem? Please describe.**
During test development when I run the tests from eclipse, I would like to quickly see in the logs which tests failed/broken

**Describe the solution you'd like**.
After the execution statistics, list the scenarios which were failed or broken. 

**Describe alternatives you've considered**
Allure report contains it, but when I run tests on server, its would be quicker to see immediately whats wrong, instead of downloading the report and opening it locally.

**Comment by valfirst** [comment]
@lammaer please try to enable logging of failures using the property:

```properties
statistics.print-failures=true
```

does it satisfy your needs?

**Comment by lammaer** [comment]
@valfirst 
Absolutely, this is great! ;)

Just a question: Where can I look after settings like this? I don't think it is in the Vividus documentation...

**Comment by lammaer** [comment]
Can be closed

**Comment by valfirst** [comment]
> Just a question: Where can I look after settings like this? I don't think it is in the Vividus documentation...

This particular feature is considered incubating, thus it's not documented
