### ISSUE TITLE
Comments reported as skipped tests if they start with Given/Then/When

### ISSUE THREAD

**Issue by lammaer** [vividus-framework/vividus#4454]
**Describe the bug**
In the execution reports, when I have a comment starting with Given/When/Then, eg "!-- When the customer enters his data"  then it is reported as skipped test step

**Expected behavior**
Comments should be totally ignored during the execution, since they are comments, even if they start with Given/When/Then. In my experience SKIPPED in the report means there was an incorretly written test step in the scenario, what is not true here, since we are talking about a comment.

**Comment by valfirst** [comment]
The described behavior is expected.
`!-- Given..` / `!-- When..` / `!-- Then..` are considered as skipped steps. If such steps should be removed from scenarios, just remove them. If steps are needed, then no reason to comment them, it's ok to comment for debugging purposes, however they shouldn't leak to codebase.
`!-- <Anything else except starting Given/When/Then>..` is considered as comment and doesn't affect test statuses.
