### ISSUE TITLE
"vividus-to-xray-exporter-0.6.0.jar" does NOT work

### ISSUE THREAD

**Issue by ElenaShvedova** [vividus-framework/vividus#4501]
![Bug](https://github.com/vividus-framework/vividus/assets/137894634/a39bbe08-761f-4ca8-bbfa-cff60747fe1a)
"vividus-to-xray-exporter-0.6.0.jar" does NOT work (screenshot "Bug" is attached).

 - Vividus version: [e.g. 0.6.0]
 - OS: [e.g. macOS Sonoma 14.0]
 - Java: JDK 17.0.8

Details:
1) Instructions used: 
https://docs.vividus.dev/vividus/latest/integrations/xray-exporter.html#_xray_export_properties

2) Properties set in "application.properties" file:

xray-exporter.project-key=<jira-project-key>
xray-exporter.json-results-directory=.../output/reports/jbehave/batch-1
xray-exporter.assignee=<assignee>
jira.vividus.project-key-regex=<jira-project-key>
jira.vividus.endpoint=<jira-url>
jira.vividus.http.auth.username=<username>
jira.vividus.http.auth.password=<password>
jira.vividus.http.socket-timeout=10000
xray-exporter.jira-instance-key=vividus
jira.vividus.http.auth.preemptive-auth-enabled=true
jira.vividus.fields-mapping.test-case-type=customfield_11400
jira.vividus.fields-mapping.manual-steps=customfield_11404

3) "application.properties" file is in the same folder as "vividus-to-xray-exporter-0.6.0.jar" file

4) ran the command:

java -jar vividus-to-xray-exporter-0.6.0.jar -Dspring.config.location=classpath:/application.properties,./application.properties

5) Received error as per screenshot attached.

**Comment by valfirst** [comment]
@ElenaShvedova please provide any details

**Comment by ElenaShvedova** [comment]
@valfirst Done.
