### ISSUE TITLE
[UI] Nested 'When I $actionType baseline with `$name`' captures area below pop-up

### ISSUE THREAD

**Issue by MrsMarta** [vividus-framework/vividus#480]
**Description**
Nested step 'When I $actionType baseline with `$name`' captures page area below pop-up instead of popup itself.

**To Reproduce**

1. Run following steps against https://members.luxresearchinc.com/:
```
Given I am on the main application page
When I find <= '1' elements by By.xpath(//*[@id='hs-eu-cookie-confirmation']) and for each element do
|step|
|When I ${visual-action} baseline with `${baseline-name}`|
```
2. Observe resulting screenshot

**Expected behavior**
Cookies pop-up area is captured on the screenshot:
<img width="960" alt="expected screenshot highlighted" src="https://user-images.githubusercontent.com/8722264/79122441-4ee39b00-7da0-11ea-9c01-43bee1b86cc7.png">

**Actual behavior**
Page area below pop-up is captured on the screenshot:
![actual screenshot](https://user-images.githubusercontent.com/8722264/79122456-55721280-7da0-11ea-9d0a-3934297ad9a2.png)

**Artifacts**
[SEO.story.txt](https://github.com/vividus-framework/vividus/files/4469611/SEO.story.txt)
[popup_allure report.zip](https://github.com/vividus-framework/vividus/files/4469604/popup_allure.report.zip)

**Execution environment:**
 - Vividus version: 0.2.2-SNAPSHOT
 - OS: Windows 10
 - Java: jdk-13.0.2_windows-x64_bin
 - Browser: Chrome 81.0.4044.92 (Official Build) (64-bit)

**Comment by Yauhenda** [comment]
Pop-up on this page has the `position='fixed'` CSS property. So it always appearing at the bottom of window.
Screenshot shooting strategy is `VIEWPORT_PASTING` by default. It used to take screenshots between scrolls and will scroll page even for one element shooting. And it takes screenshot of area where element should appears but it fixed at the bottom and not move when page scrolling.
To solve this you can use `SIMPLE` shooting strategy that wouldn't scroll page while shooting.

```
Given I am on the main application page
When I find <= '1' elements by By.xpath(//*[@id='hs-eu-cookie-confirmation']) and for each element do
{headerSeparator=!,valueSeparator=!}
!step!
!When I ${visual-action} baseline with `${baseline-name}` using screenshot configuration:
|screenshotShootingStrategy|
|SIMPLE                    |!
```
![Screenshot](https://user-images.githubusercontent.com/41984237/79384717-12669980-7f70-11ea-9cdb-9cce6818da53.png)

**Comment by MrsMarta** [comment]
Thanks @Yauhenda, closing the ticket as provided solution works perfectly
