### ISSUE TITLE
Implement capability for JSON transformation to a plain structure

### ISSUE THREAD

**Issue by remiprink** [vividus-framework/vividus#496]
In order to perform ETL testing with NoSQL sources, there should be a possibility to transform the result of query execution against MongoDB to plain structure.
Requirements:
- Possibility to choose object names to include into resulting table (e.g. via JSONPath)
- Possibility to save resulting table into any plain structure (e.g. CSV)

**Comment by valfirst** [comment]
@remiprink please take a look: https://github.com/vividus-framework/vividus/pull/498/files
