### ISSUE TITLE
Incorrect order of execution of Table transformers

### ISSUE THREAD

**Issue by draker94** [vividus-framework/vividus#5438]
When we're trying to load external table with transformers and apply story transformers above, it firstly apply story transformer and only then apply external transformers.

**To Reproduce**
**Story**
```
Lifecycle:
Examples:
{transformer=FILTERING, column.urls=.+not-exist.+}
/story/experimental/data/links.table

Scenario: Use filtered links
Given I am on page with URL `<urls>`
```

**Table**
```
{transformer=FROM_HTML, column=urls, variableName=sourceCode, xpathSelector=//a/@href}
```
(expected that story will be executed zero times due to empty table)

Log:
[log.txt](https://github.com/user-attachments/files/17407858/log.txt)

**Expected behavior**
Transformers on the Story/Scenario level should be executed after external transformers.

**Comment by valfirst** [comment]
Fixed by #5489
