### ISSUE TITLE
To add possibility to stop running further batches of tests if the first batch failed:

### ISSUE THREAD

**Issue by VolhaHoman** [vividus-framework/vividus#582]
**Is your feature request related to a problem? Please describe.**
Due to the problem that a failed scenario about logging in the application (for UI) or getting SSO token (for API) blocks further pipelines running and even postpones Jenkins restart, we need to have further running of the rest test bathes to be stopped, **if the first batch about login or getting token failed.**
 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VolhaHoman** [comment]
created by mistake

**Comment by valfirst** [comment]
Duplicate of #583
