### ISSUE TITLE
Wrong composite step executes in case 2 steps have similar wording

### ISSUE THREAD

**Issue by remiprink** [vividus-framework/vividus#600]
**Description**
In case user creates 2 different composite steps with similar wording, the step that is located 1st in the file starts to execute even if the user is calling the 2nd one.

**To Reproduce**
Please, see the story and composite.steps file attached.
composite.steps file comtains 2 steps going one right after another:
`When I generate parquet with the name '$fileName' using schema '$schema' and data '$data'`
and
`When I generate parquet with the name '$fileName' for table '$table' using schema '$schema' and data '$data'`
The second one is invoked in the story. However, the first one executes (can bee seen in the test result report)

**Artifacts**
[defect.zip](https://github.com/vividus-framework/vividus/files/4663835/defect.zip)

**Execution environment (please complete the following information):**
 - Vividus version: 0.2.3-SNAPSHOT
 - OS: Win 10
 - Java: Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)

**Comment by remiprink** [comment]
priority - p3

**Comment by uarlouski** [comment]
Second composite step should be assigned priority, please see https://jbehave.org/reference/stable/composite-steps.html at the end of the page
https://jbehave.org/reference/stable/prioritising-steps.html - here is steps priority explanation

**Comment by remiprink** [comment]
Thank you, works fine after applying priorities, can be closed
