### ISSUE TITLE
Add step to verify the TLS protocol versions supported by server

### ISSUE THREAD

**Issue by HelgiSikoRa** [vividus-framework/vividus#681]
**Is your feature request related to a problem? Please describe.**
Server could support TLSv1.1 and TLSv1.0 protocols which is not recommended using for now, therefore we should verify that among all TLS protocols which are currently enabled for use on connection is not those version. 

**Describe the solution you'd like**
Then the number of the TLS protocol version with the name 'protocolName' is = 0
Then the number of the TLS protocol version with the name 'protocolName' is >= 1

As an option for implementing this feature maybe the method getEnabledProtocols() from  SSLSocket class in javax.net.ssl package can help you. (SSLSocketFactory() -> createSocket(String host, int port))

**Comment by uarlouski** [comment]
https://docs.vividus.dev/vividus/latest/plugins/plugin-rest-api.html#_verify_secure_protocols_supported_by_server
