### ISSUE TITLE
Text parameter for template is not resolving fully if eol character used

### ISSUE THREAD

**Issue by remiprink** [vividus-framework/vividus#712]
**Description**
In case user uses eol character inside of value of parameter for freemarker template, the value is resolving only before the end of line, all other characters are cut out.

**To Reproduce**
1. Create ftl template, which will consume text parameter
2. Initialize template in a story, as a value for parameter define text that has end of line characters

**Expected result**
Text parameter is resolved fully in template

**Actual result**
Text parameter is resolved only 'till the first eol character, all other text is cut off (please, see the screenshot attached)

**Artifacts**
![Screenshot_1490](https://user-images.githubusercontent.com/15046148/86231189-d4563a80-bb9a-11ea-8e77-22a509b9c491.png)

**Execution environment:**
 - Vividus version: 0.2.3-SNAPSHOT
 - OS: Win 10
 - Java: 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**Comment by remiprink** [comment]
priority - p3

**Comment by valfirst** [comment]
https://docs.vividus.dev/vividus/latest/glossary.html#_using_values_with_line_breaks:
> Line break is a default separator for rows in `ExamplesTable`, that’s why they can’t be added as is to the data. In order to put value with line breaks to `ExamplesTable` escape sequences (a character preceded by a backslash `\` is an escape sequence) must be used.
