### ISSUE TITLE
Increase the usability of Allure report by adding an extra portion of information

### ISSUE THREAD

**Issue by DaniilKalkaev** [vividus-framework/vividus#81]
Allure report will be more useful for teammates if you will add the following information to report:
1. SUITE	
2. ENVIRONMENTS	
3. PROFILE	
4. META_FILTERS
5. INCLUDE/EXCLUDE PATTERNS
6. MAIN APPLICATION URL
7. ESTABLISH/COMPARE AGAINST

**Comment by valfirst** [comment]
Waiting for https://github.com/allure-framework/allure2/pull/1009
