### ISSUE TITLE
Implement configurable browser behavoiur: close after each new scenario

### ISSUE THREAD

**Issue by dKatechev** [vividus-framework/vividus#866]
Current behavior:
Browser window is the only through the story.

Desired behavior:
Browser window should be closed after Scenario.
Browser window should be also closed after Scenario Examples iteration.
Can be tuned for test run with configurable property.

**Comment by valfirst** [comment]
New properties are added:
 - [web-application.session-scope](https://docs.vividus.dev/vividus/0.2.8-SNAPSHOT/plugins/plugin-web-app.html#_properties)
- [mobile-application.session-scope](https://docs.vividus.dev/vividus/0.2.8-SNAPSHOT/plugins/plugin-mobile-app.html#_properties)
