### ISSUE TITLE
Integrate Vividus with Report Portal v.5.0 so that logs and screenshots are available

### ISSUE THREAD

**Issue by irinakartun** [vividus-framework/vividus#975]
**Steps to reproduce:**
- add next dependency into build.gradle:
compile group: 'org.vividus', name: 'vividus-agent-reportportal', version: '0.2.5'

- create reportportal.properties file with values:
system.rp.enable=true
system.rp.endpoint=https://reportportal.epam.com
system.rp.uuid=***
system.rp.launch=LOCAL_LAUNCH
system.rp.project=***

-run stories -> launch is created in RP, stack trace and attachments are not available for failed steps

![image](https://user-images.githubusercontent.com/15156585/94815960-cfa45b00-0403-11eb-9d41-ff49c16cb979.png)

**Comment by valfirst** [comment]
Partially blocked by https://github.com/apache/logging-log4j2/pull/440
